services:
  postgres:
    image: postgres:16-alpine
    container_name: ellp-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ellp_dev
      POSTGRES_USER: ellp
      POSTGRES_PASSWORD: ellp123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
